spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.114/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true 
  redis:
    host: 192.168.43.114
    port: 6379
server:
  servlet:
    context-path: /sell
wechat: 
  mpAppId: wxe4b26b95fab3ecb4
  mpAppSecret: 9b7ab306a2414f679b6bf8de1eb8f081